services:
  # Service 1: La base de données PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: postgres_db_mspr
    environment:
      - POSTGRES_USER=mspr_user
      - POSTGRES_PASSWORD=Mspr6.1@
      - POSTGRES_DB=mspr_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service 2: Votre application (API)
  app:
    container_name: fast_api_mspr
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.api

volumes:
  postgres_data: